apiVersion: v1
kind: Service
metadata:
  name: akka-server
  labels:
    app: akka-server
spec:
  selector:
    app: akka-server
  type:   NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 31122
      targetPort: 8080